server:
  port: 6001
spring:
  application:
    name: sleuth-server
  boot:
    admin:
      url: http://127.0.0.1:6002 

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:6003/eureka/
      
management:
  security:
    enabled: false