server:
  port: 8002
  session:
    timeout: 60 
spring:
  application:
    name: prefecture-server
  boot: 
    admin:
      url: http://192.168.1.142:6002
eureka:
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    fetch-registry: true 
    serviceUrl:
      defaultZone: http://192.168.1.142:6003/eureka/
feign:
  hystrix:
    enabled: true
ribbon:
  ConnectTimeout: 6000
  ReadTimeout: 60000
hystrix: 
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 35000
            ribbon:
              ReadTimeout: 30000
              ConnectTimeout: 35000    
 
master-db:   
  url: jdbc:mysql://192.168.1.218:3306/db_linkmore?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF8&useSSL=false
  username: root
  password: Linkmore@2018
  driver-class-name: com.mysql.jdbc.Driver  
  initial-size: 10
  min-idle: 10
  max-active: 20 
  max-wait: 60000 
  time-between-eviction-runs-millis: 60000 
  min-evictable-idle-time-millis: 30000
  validation-query: select 'x'
  test-while-idle: true
  test-on-borrow: false
  test-on-return: false 
  pool-prepared-statements: true
  max-pool-prepared-statement-per-connection-size: 20 
  filters: stat,wall,slf4j 
  connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  
cluster-db:   
  url: jdbc:mysql://192.168.1.219:3306/db_linkmore?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF8
  username: root
  password: Linkmore@2018
  driver-class-name: com.mysql.jdbc.Driver  
  initial-size: 10
  min-idle: 10
  max-active: 20 
  max-wait: 60000 
  time-between-eviction-runs-millis: 60000 
  min-evictable-idle-time-millis: 30000
  validation-query: select 'x'
  test-while-idle: true
  test-on-borrow: false
  test-on-return: false 
  pool-prepared-statements: true
  max-pool-prepared-statement-per-connection-size: 20 
  filters: stat,wall,slf4j 
  connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000 

security:
  basic:
    enabled: false
    
redis:
  host: 192.168.1.218
  port: 6379
  database: 4
  timeout: 5000
  password: ppyx1234
  pool-max-active: 500
  pool-max-wait: -1
  pool-max-idle: 100
  pool-min-idle: 5
  test-while-idle: true
  test-on-borrow: true
  test-on-create: true 
  sentinel-master: mymaster
  sentinel-nodes: 192.168.1.219:26379 
  channel: prefecture
  
lock:
  app-secret: b36441d95239bc919eac75aa18c0c54b
  app-id: 95b94e076c8546db9f329bbd8c0f2030
  linkemore-lock-url: http://open-api.linkmoreparking.cn
logging:
  level:
     cn.linkmore.prefecture.dao : debug

swagger:
  enable: true
  title: 凌猫车区车位服务接口文档
  description: 本文档为内部文档，仅供内部前端及测试人员参考。 完全基于RESTful接口说明
  version: 2.0
  service-url: http://www.linkmoreparking.com
  contact: 凌猫停车 
  base-package: cn.linkmore.prefecture.controller.app,cn.linkmore.prefecture.controller.staff

strategyfee: 
  url: 
    fee: http://192.168.1.76:8086/charge/api/reckon_charge_price
    list: http://192.168.1.76:8086/charge/api/get_charge_list
    detail: http://192.168.1.76:8086//charge/api/get_charge_detail
  fee-code: 987656
  fee-secret: 99876505523