server:
  port: 9000 
spring:
  application:
    name: ops-server
  boot: 
    admin:
      url: http://192.168.1.223:6002
eureka:
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    fetch-registry: true 
    serviceUrl:
      defaultZone: http://192.168.1.223:6003/eureka/

feign:
  hystrix:
    enabled: true

ribbon:
  ConnectTimeout: 6000
  ReadTimeout: 60000
hystrix: 
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 30000
            ribbon:
              ReadTimeout: 30000
              ConnectTimeout: 60000
    
security:
  basic:
    enabled: false 
    
multipart:  
  enabled: true  
  max-file-size: 50mb  
  max-request-size: 50mb 
  
swagger:
  enable: true
  title: 运营管理后台接口文档
  description: 本文档为内部文档，仅供内部前端及测试人员参考。 完全基于RESTful接口说明
  version: 2.0
  service-url: http://www.linkmoreparking.com
  contact: 凌猫停车