server:
  port: 9000 
spring:
  application:
    name: ops-server
  boot: 
    admin:
      url: http://192.168.1.64:6002
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    fetch-registry: true 
    serviceUrl:
      defaultZone: http://192.168.1.64:6003/eureka/ 

feign:
  hystrix:
    enabled: true
    
swagger:
  enable: true
  title: 运营管理后台接口文档
  description: 本文档为内部文档，仅供内部前端及测试人员参考。 完全基于RESTful接口说明
  version: 2.0
  service-url: http://www.linkmoreparking.com
  contact: 凌猫停车