server:
  port: 9001 
spring:
  application:
    name: mini-program-server
  boot: 
    admin:
      url: http://127.0.0.1:6002
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  zipkin:
    rabbitmq:
      queue: zipkin 
      
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    fetch-registry: true 
    serviceUrl:
      defaultZone: http://127.0.0.1:6003/eureka/ 
      
feign:
  hystrix:
    enabled: true      


swagger:
  enable: true
  title: 小程序前端应用接口
  description: 本文档适应微信小程序前端调用 完全基于RESTful接口说明
  version: 2.0
  service-url: http://www.linkmoreparking.com
  contact: 凌猫停车
  class-path: cn.linkmore.mini.controller
 