server:
  port: 6005
spring:
  application:
    name: zuul-server
  boot: 
    admin:
      url: http://192.168.1.64:6002

eureka:
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    fetch-registry: true 
    serviceUrl:
      defaultZone: http://192.168.1.64:6003/eureka/  

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

zuul:
  host:
    max-per-route-connections: 10000
    max-total-connections: 10000
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  routes:  
    user-app-api:
      path: /user-app/**  
      serviceId: user-app-server
      sensitiveHeaders: Authorization
    staff-app-api:
      path: /staff-app/**  
      serviceId: staff-app-server
    wxapp-api:
      path: /wxapp/**  
      serviceId: wxapp-server 
    ops-api:
      path: /ops/**  
      serviceId: ops-server 
    cloud-admin:
      path: /cloud-admin/**
      serviceId: admin-server
    cloud-eureka:
      path: /cloud-eureka/**
      serviceId: eureka-server
  
  
management:
  security:
    enabled: false