server:
  port: 8003 
spring:
  application:
    name: account-server
  boot: 
    admin:
      url: http://127.0.0.1:6002
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    fetch-registry: true 
    serviceUrl:
      defaultZone: http://127.0.0.1:6003/eureka/ 

feign:
  hystrix:
    enabled: true 
          
master-db:   
  url: jdbc:mysql://192.168.1.60:3306/linkmore?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF8
  username: ppyx_dev
  password: PPYX_dev123 
  driver-class-name: com.mysql.jdbc.Driver  
  initial-size: 10
  min-idle: 10
  max-active: 20 
  max-wait: 60000 
  time-between-eviction-runs-millis: 60000 
  min-evictable-idle-time-millis: 30000
  validation-query: select 'x'
  test-while-idle: true
  test-on-borrow: false
  test-on-return: false 
  pool-prepared-statements: true
  max-pool-prepared-statement-per-connection-size: 20 
  filters: stat,wall,slf4j 
  connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  
cluster-db:   
  url: jdbc:mysql://192.168.1.60:3306/linkmore?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF8
  username: ppyx_dev
  password: PPYX_dev123
  driver-class-name: com.mysql.jdbc.Driver  
  initial-size: 10
  min-idle: 10
  max-active: 20 
  max-wait: 60000 
  time-between-eviction-runs-millis: 60000 
  min-evictable-idle-time-millis: 30000
  validation-query: select 'x'
  test-while-idle: true
  test-on-borrow: false
  test-on-return: false 
  pool-prepared-statements: true
  max-pool-prepared-statement-per-connection-size: 20 
  filters: stat,wall,slf4j 
  connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000 

redis:
  host: 192.168.1.63
  port: 7001
  database: 1
  timeout: 5000
  password: ppyx!@#
  pool-max-active: 500
  pool-max-wait: -1
  pool-max-idle: 100
  pool-min-idle: 5
  test-while-idle: true
  test-on-borrow: true
  test-on-create: true 
  sentinel-master: ppyxmaster
  sentinel-nodes: 192.168.1.61:26379 