server:
  port: 9007
spring:
  application:
    name: turbine-server

turbine:
  app-config: eureka-consumer-ribbon-hystrix
  cluster-name-expression: "default"
  combine-host-port: true

#must dependent eureka server , it used be as service cluster monitor
eureka:
  client:
    service-url:
      default-zone: http://127.0.0.1:9003/eureka/
