server:
  port: 6007
spring:
  application:
    name: turbine-server

turbine:
  appConfig: eureka-consumer-ribbon-hystrix
  clusterNameExpression: "default"
  combineHostPort: true

#must dependent eureka server , it used be as service cluster monitor
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:6003/eureka/
