server:
  port: 9002
spring:
  application:
    name: user-app-server
  boot: 
    admin:
      url: http://192.168.1.64:6002 
eureka:
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    fetch-registry: true 
    serviceUrl:
      defaultZone: http://192.168.1.64:6003/eureka/ 
feign:
  hystrix:
    enabled: true  

swagger:
  enable: true
  title: 凌猫停车个人版APP接口文档
  description: 本文档为内部文档，仅供内部前端及测试人员参考。 完全基于RESTful接口说明
  version: 2.0
  service-url: http://www.linkmoreparking.com
  contact: 凌猫停车 
  
  
redis:
  host: 192.168.1.63
  port: 7001
  database: 1
  timeout: 5000
  password: ppyx!@#
  pool-max-active: 500
  pool-max-wait: -1
  pool-max-idle: 100
  pool-min-idle: 5
  test-while-idle: true
  test-on-borrow: true
  test-on-create: true 
  sentinel-master: ppyxmaster
  sentinel-nodes: 192.168.1.61:26379  