server:
  port: 6005
spring:
  application:
    name: zuul-server
  boot: 
    admin:
      url: http://192.168.1.150:6002

eureka:
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    fetch-registry: true 
    serviceUrl:
      defaultZone: http://192.168.1.150:6003/eureka/  

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

zuul:
  host:
    max-per-route-connections: 10000
    max-total-connections: 10000
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  routes:  
    order:
      path: /order/**  
      serviceId: order-server
      sensitiveHeaders: Authorization
    prefecture:
      path: /prefecture/**  
      serviceId: prefecture-server
      sensitiveHeaders: Authorization
    common:
      path: /common/**  
      serviceId: common-server 
      sensitiveHeaders: Authorization
    account:
      path: /account/**  
      serviceId: account-server 
      sensitiveHeaders: Authorization
    coupon:
      path: /coupon/**  
      serviceId: coupon-server 
      sensitiveHeaders: Authorization
    cloud-admin:
      path: /cloud-admin/**
      serviceId: admin-server
    cloud-eureka:
      path: /cloud-eureka/**
      serviceId: eureka-server 
  
security:
  basic:
    enabled: false 
    
redis:
  host: 192.168.1.218
  port: 6379
  database: 1
  timeout: 5000
  password: ppyx1234
  pool-max-active: 500
  pool-max-wait: -1
  pool-max-idle: 100
  pool-min-idle: 5
  test-while-idle: true
  test-on-borrow: true
  test-on-create: true 
  sentinel-master: mymaster
  sentinel-nodes: 192.168.1.219:26379 