server:
  port: 6005
  session:
    timeout: 60
spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  application:
    name: zuul-server
  boot: 
    admin:
      url: http://192.168.1.223:6002

eureka:
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    fetch-registry: true 
    serviceUrl:
      defaultZone: http://192.168.1.223:6003/eureka/  
 

ribbon:
  ConnectTimeout: 6000
  ReadTimeout: 60000
hystrix: 
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 30000
            ribbon:
              ReadTimeout: 30000
              ConnectTimeout: 60000
 
zuul:
  semaphore:
    maxSemaphores: 3000
  host:
    max-per-route-connections: 30000
    max-total-connections: 30000
    connect-timeout-millis: 30000
    socket-timeout-millis: 30000
  routes:  
    order:
      path: /api/order/**  
      serviceId: order-server
      sensitiveHeaders: Authorization
    prefecture:
      path: /api/prefecture/**  
      serviceId: prefecture-server
      sensitiveHeaders: Authorization
    common:
      path: /api/common/**  
      serviceId: common-server 
      sensitiveHeaders: Authorization
    account:
      path: /api/account/**  
      serviceId: account-server 
      sensitiveHeaders: Authorization
    coupon:
      path: /api/coupon/**  
      serviceId: coupon-server 
      sensitiveHeaders: Authorization
    enterprise:
      path: /api/enterprise/**  
      serviceId: enterprise-server 
      sensitiveHeaders: Authorization    
    ops:
      path: /admin/**  
      serviceId: ops-server 
      sensitiveHeaders: Authorization 
security:
  basic:
    enabled: false 
    
redis:
  host: 192.168.1.218
  port: 6379
  database: 2
  timeout: 5000
  password: ppyx1234
  pool-max-active: 500
  pool-max-wait: -1
  pool-max-idle: 100
  pool-min-idle: 5
  test-while-idle: true
  test-on-borrow: true
  test-on-create: true 
  sentinel-master: mymaster
  sentinel-nodes: 192.168.1.219:26379
  channel: zuul