server:
  port: 9003 
spring:
  application:
    name: staff-app-server
  boot: 
    admin:
      url: http://192.168.1.64:6002
eureka:
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    fetch-registry: true 
    serviceUrl:
      defaultZone: http://192.168.1.64:6003/eureka/
      
swagger:
  enable: true
  title: 凌猫停车管理版APP接口文档
  description: 本文档为内部文档，仅供内部前端及测试人员参考。 完全基于RESTful接口说明
  version: 2.0
  service-url: http://www.linkmoreparking.com
  contact: 凌猫停车  