server:
  port: 9003 
spring:
  application:
    name: staff-app-server
  boot: 
    admin:
      url: http://127.0.0.1:6002
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    fetch-registry: true 
    serviceUrl:
      defaultZone: http://127.0.0.1:6003/eureka/
      
swagger:
  title: Staff app api
  description: Staff app api 2.x
  version: 1.1.0.RELEASE
  license: Apache License, Version 2.0
  licenseUrl: https://www.apache.org/licenses/LICENSE-2.0.html
  termsOfServiceUrl: https://api.linkmoreparking.com
  contact:
    name: Linkmore
    url: https://www.linkmoreparking.com
    email: service@papayixing.com
  base-package: cn.linkmore