server:
  port: 9001
  session:
    timeout: 600
spring:
  application:
    name: notice-server 
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true 
  boot: 
    admin:
      url: http://192.168.1.223:6002
eureka:
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    fetch-registry: true 
    serviceUrl:
      defaultZone: http://192.168.1.223:6003/eureka/
feign:
  hystrix:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true 
    
ribbon:
  ConnectTimeout: 6000
  ReadTimeout: 60000
hystrix: 
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 30000
            ribbon:
              ReadTimeout: 30000
              ConnectTimeout: 60000 
security:
  basic:
    enabled: false
    
redis:
  host: 192.168.1.218
  port: 6379
  database: 0
  timeout: 5000
  password: ppyx1234
  pool-max-active: 500
  pool-max-wait: -1
  pool-max-idle: 100
  pool-min-idle: 5
  test-while-idle: true
  test-on-borrow: true
  test-on-create: true 
  sentinel-master: mymaster
  sentinel-nodes: 192.168.1.219:26379  
  channel: notice  
