server:
  port: 6003
spring:
  application:
    name: eureka-server
  boot: 
    admin:
      url: http://127.0.0.1:6002
security:
  basic:
    enabled: true
  user:
    name: linkmore
    password: Linkmore@2018
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ 