server:
  port: 6003
spring:
  application:
    name: eureka-server
  boot: 
    admin:
      url: http://192.168.1.64:6002 
eureka:
  instance:
    hostname: 192.168.1.64
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ 