server:
  port: 6003
spring:
  application:
    name: eureka-server
  boot: 
    admin:
      url: http://192.168.1.64:6002 
eureka:
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    hostname: ${spring.cloud.client.ipAddress}
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 2
  server:
    responseCacheUpdateInvervalMs: 3000
    responseCacheAutoExpirationInSeconds: 30
    eviction-interval-timer-in-ms: 3000
    enable-self-preservation: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ 