server:
  port: 8001 
spring:
  application:
    name: common-server
  boot: 
    admin:
      url: http://127.0.0.1:6002
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    fetch-registry: true 
    serviceUrl:
      defaultZone: http://127.0.0.1:6003/eureka/ 

feign:
  hystrix:
    enabled: true