server:
  port: 6004
  
spring:
  application:
    name: config-server
  boot: 
    admin:
      url: http://127.0.0.1:6002 
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: config-repo 
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:6003/eureka/

management:
  security:
    enabled: false

#enforce config-service security
security:
  user:
    name: linkmore
    password: linkmore@2018

  
