server:
  port: 6004
  
spring:
  application:
    name: config-server
  boot: 
    admin:
      url: http://127.0.0.1:6002
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/backkoms/spring-cloud-repo
          search-paths: repo 
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:6003/eureka/

management:
  security:
    enabled: false

#enforce config-service security
security:
  user:
    name: user
    password: yourPW

  
