server:
  port: 6002
spring:
  application:  
    name: admin-server
  boot:
    admin:
      context-path: /index
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:6003/eureka/
  
management:
  security:
    enabled: false