server:
  port: 6002
spring:
  application:  
    name: admin-server
  boot:
    admin:
      context-path: /index
eureka:
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    fetch-registry: true 
    serviceUrl:
      defaultZone: http://192.168.1.232:6003/eureka/
  
management:
  security:
    enabled: false